@ContosoPizza_HostAddress = http://localhost:5051

GET {{ContosoPizza_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{ContosoPizza_HostAddress}}/pizza
Content-Type: application/json

{
  "name": "Pepperoni",
  "isGlutenFree": false,
  "price": 12.99
}