@InsightDesk_HostAddress = http://localhost:5051

GET {{InsightDesk_HostAddress}}/weatherforecast/
Accept: application/json

###


POST {{InsightDesk_HostAddress}}/pizza
Content-Type: application/json

{
  "name": "Pepperoni",
  "isGlutenFree": false,
  "price": 12.99
}